### PR TITLE
First attempt at addressing issue #12

### PR DESCRIPTION
**Pull request by jameskermode**

### CODE REVIEW

**Comment by cortner** [comment]
Yeey! My first pull request ever :). I'll look at it tonight.

**Comment by cortner** [comment]
hi james - would you be willing to just strip the outputs before I merge it?

**Comment by jameskermode** [comment]
Yup, sure, will do it tomorrow morning.

**Comment by jameskermode** [comment]
Done, and also added a `JulipOptimizer` wrapper that allows Optim.jl solvers to be called from Python. Should be ready to merge.

**Comment by cortner** [comment]
when I am done with stress, then we should add it to the interface and make sure it is compatible with ASE. (Cell shape optimisation is *nasty*!)

**Comment by jameskermode** [comment]
Yes it is - Good idea, but will need to think about best way to do this. In ASE, the canonical way to do variable cell minimisation is by wrapping the Atoms with a generalised atoms that has extra DoFs and force components: https://gitlab.com/ase/ase/blob/master/ase/constraints.py#L1288

**Comment by cortner** [comment]
I think that can be done more elegantly - and much more generally - by just defining an `atoms <-> dofs` mapping as part of any `Atoms` object.

**Pull request merged**
