### PR TITLE
Momentum dofs

### PR DESCRIPTION
**Pull request by cortner**
this should implement #32 

Before merging I want to implement a simple newtonian dynamics example.

### CODE REVIEW

**Comment by cortner** [comment]
this should now be ready to merge

**Comment by jameskermode** [comment]
Once the tests pass :-)

**Comment by cortner** [comment]
I think I need to tag a new version of PyAMG for that. I'll do that asap

**Comment by jameskermode** [comment]
Could also edit "REQUIRE" or ".travis.yml" in repo root to do a `Pkg.clone("PyAMG")` rather than ` Pkg.add()`

**Comment by cortner** [comment]
The problem is that I am using a branch of Optim that isn't tagged or even merged.  I am slowly getting sick of trying to modify Optim instead of writing my own code.

**Comment by cortner** [comment]
finally.

**Pull request merged**
