### PR TITLE
install gfortran on osx travis

### PR DESCRIPTION
**Pull request by tkelman**

### CODE REVIEW

**Comment by tkelman** [comment]
looks like it times out now, any way to parallelize the tests a bit?

**Comment by cortner** [comment]
I don't have experience with parallelisation and my initial naive attempts failed. Can you point me to a model that I could follow?

**Comment by tkelman** [comment]
maybe as simple as starting julia with `-p 4` and doing `@parallel` here https://github.com/libAtoms/JuLIP.jl/blob/6f8749635e79aebbc067f23734fd7d5c65f65355/test/runtests.jl#L32 ?

**Comment by cortner** [comment]
that is what I tried.

**Comment by tkelman** [comment]
what went wrong?

**Comment by cortner** [comment]
I used `@everywhere` to load all modules and data onto all workers and then `@parallel` where you suggested and get the following:
```
Sunrise:test ortner$ j5 -p 4 runtests.jl
WARNING: 'gpaw' Python module cannot be imported: JuLIP.DFT disabled
WARNING: replacing module JuLIP
WARNING: replacing module JuLIP
WARNING: replacing module JuLIP
WARNING: replacing module JuLIP
WARNING: Method definition zero(Type{StaticArrays.SVector{3, #T<:Any}}) in module JuLIP at /Users/ortner/.julia/v0.5/JuLIP/src/arrayconversions.jl:26 overwritten in module JuLIP at /Users/ortner/.julia/v0.5/JuLIP/src/arrayconversions.jl:26.
WARNING: Method definition convert(Type{Array{#T<:Any, 2}}, Array{StaticArrays.SVector{3, #T<:Any}, 1}) in module JuLIP at /Users/ortner/.julia/v0.5/JuLIP/src/arrayconversions.jl:100 overwritten in module JuLIP at /Users/ortner/.julia/v0.5/JuLIP/src/arrayconversions.jl:100.
WARNING: Method definition convert(Type{Array{StaticArrays.SVector{3, #T<:Any}, 1}}, Array{#T<:Any, 2}) in module JuLIP at /Users/ortner/.julia/v0.5/JuLIP/src/arrayconversions.jl:101 overwritten in module JuLIP at /Users/ortner/.julia/v0.5/JuLIP/src/arrayconversions.jl:101.
WARNING: Method definition zero(Type{StaticArrays.SVector{3, #T<:Any}}) in module JuLIP at /Users/ortner/.julia/v0.5/JuLIP/src/arrayconversions.jl:26 overwritten in module JuLIP at /Users/ortner/.julia/v0.5/JuLIP/src/arrayconversions.jl:26.
WARNING: Method definition zero(Type{StaticArrays.SVector{3, #T<:Any}}) in module JuLIP at /Users/ortner/.julia/v0.5/JuLIP/src/arrayconversions.jl:26 overwritten in module JuLIP at /Users/ortner/.julia/v0.5/JuLIP/src/arrayconversions.jl:26.
WARNING: Method definition convert(Type{Array{#T<:Any, 2}}, Array{StaticArrays.SVector{3, #T<:Any}, 1}) in module JuLIP at /Users/ortner/.julia/v0.5/JuLIP/src/arrayconversions.jl:100 overwritten in module JuLIP at /Users/ortner/.julia/v0.5/JuLIP/src/arrayconversions.jl:100.
WARNING: Method definition convert(Type{Array{StaticArrays.SVector{3, #T<:Any}, 1}}, Array{#T<:Any, 2}) in module JuLIP at /Users/ortner/.julia/v0.5/JuLIP/src/arrayconversions.jl:101 overwritten in module JuLIP at /Users/ortner/.julia/v0.5/JuLIP/src/arrayconversions.jl:101.
WARNING: Method definition convert(Type{Array{#T<:Any, 2}}, Array{StaticArrays.SVector{3, #T<:Any}, 1}) in module JuLIP at /Users/ortner/.julia/v0.5/JuLIP/src/arrayconversions.jl:100 overwritten in module JuLIP at /Users/ortner/.julia/v0.5/JuLIP/src/arrayconversions.jl:100.
WARNING: Method definition convert(Type{Array{StaticArrays.SVector{3, #T<:Any}, 1}}, Array{#T<:Any, 2}) in module JuLIP at /Users/ortner/.julia/v0.5/JuLIP/src/arrayconversions.jl:101 overwritten in module JuLIP at /Users/ortner/.julia/v0.5/JuLIP/src/arrayconversions.jl:101.
WARNING: Method definition zero(Type{StaticArrays.SVector{3, #T<:Any}}) in module JuLIP at /Users/ortner/.julia/v0.5/JuLIP/src/arrayconversions.jl:26 overwritten in module JuLIP at /Users/ortner/.julia/v0.5/JuLIP/src/arrayconversions.jl:26.
WARNING: Method definition convert(Type{Array{#T<:Any, 2}}, Array{StaticArrays.SVector{3, #T<:Any}, 1}) in module JuLIP at /Users/ortner/.julia/v0.5/JuLIP/src/arrayconversions.jl:100 overwritten in module JuLIP at /Users/ortner/.julia/v0.5/JuLIP/src/arrayconversions.jl:100.
WARNING: Method definition convert(Type{Array{StaticArrays.SVector{3, #T<:Any}, 1}}, Array{#T<:Any, 2}) in module JuLIP at /Users/ortner/.julia/v0.5/JuLIP/src/arrayconversions.jl:101 overwritten in module JuLIP at /Users/ortner/.julia/v0.5/JuLIP/src/arrayconversions.jl:101.
WARNING: 'gpaw' Python module cannot be imported: JuLIP.DFT disabled
WARNING: 'gpaw' Python module cannot be imported: JuLIP.DFT disabled
WARNING: 'gpaw' Python module cannot be imported: JuLIP.DFT disabled
WARNING: 'gpaw' Python module cannot be imported: JuLIP.DFT disabled
ERROR: LoadError: On worker 2:
LoadError: LoadError: UndefVarError: AbstractCalculator not defined
 in include_string at ./loading.jl:441
 in jlcall_include_string_40716 at /Users/ortner/gits/julia/usr/lib/julia/sys.dylib:?
 in include_from_node1 at ./loading.jl:491
 in jlcall_include_from_node1_20345 at /Users/ortner/gits/julia/usr/lib/julia/sys.dylib:?
 in include_string at ./loading.jl:441
 in jlcall_include_string_40716 at /Users/ortner/gits/julia/usr/lib/julia/sys.dylib:?
 in include_from_node1 at ./loading.jl:491
 in jlcall_include_from_node1_20345 at /Users/ortner/gits/julia/usr/lib/julia/sys.dylib:?
 in eval at ./boot.jl:234
 in jlcall_eval_19968 at /Users/ortner/gits/julia/usr/lib/julia/sys.dylib:?
 in require at ./loading.jl:415
 in jlcall_require_22569 at /Users/ortner/gits/julia/usr/lib/julia/sys.dylib:?
 in eval at ./boot.jl:234
 in jlcall_eval_19968 at /Users/ortner/gits/julia/usr/lib/julia/sys.dylib:?
 in eval_ew_expr at ./multi.jl:1981
 in #645 at ./multi.jl:1421
 in run_work_thunk at ./multi.jl:1001
 in macro expansion at ./multi.jl:1421 [inlined]
 in #644 at ./event.jl:68
while loading /Users/ortner/.julia/v0.5/JuLIP/src/DFT.jl, in expression starting on line 10
while loading /Users/ortner/.julia/v0.5/JuLIP/src/JuLIP.jl, in expression starting on line 13
 in #remotecall_fetch#626(::Array{Any,1}, ::Function, ::Function, ::Base.Worker, ::Expr, ::Vararg{Expr,N}) at ./multi.jl:1070
 in remotecall_fetch(::Function, ::Base.Worker, ::Expr, ::Vararg{Expr,N}) at ./multi.jl:1062
 in #remotecall_fetch#629(::Array{Any,1}, ::Function, ::Function, ::Int64, ::Expr, ::Vararg{Expr,N}) at ./multi.jl:1080
 in remotecall_fetch(::Function, ::Int64, ::Expr, ::Vararg{Expr,N}) at ./multi.jl:1080
 in (::##1#3)() at ./multi.jl:1967

...and 3 other exceptions.

 in sync_end() at ./task.jl:311
 in macro expansion; at ./multi.jl:1977 [inlined]
 in anonymous at ./<missing>:?
 in include_from_node1(::String) at ./loading.jl:488
 in include_from_node1(::String) at /Users/ortner/gits/julia/usr/lib/julia/sys.dylib:?
 in process_options(::Base.JLOptions) at ./client.jl:265
 in _start() at ./client.jl:321
 in _start() at /Users/ortner/gits/julia/usr/lib/julia/sys.dylib:?
while loading /Users/ortner/.julia/v0.5/JuLIP/test/runtests.jl, in expression starting on line 2
```

Quite possibly just a bug and not a fundamental problem - I just didn't write the tests to be run in parallel. (but maybe that shouldn't matter?) But I haven't had the time yet to track this down.

**Pull request merged**
