### PR TITLE
Hessians

### PR DESCRIPTION
**Pull request by cortner**
found the bug in @git4lei's `hessian` branch.

 This implements hessians for pair potentials. We should be able to add EAM very easily as well and we can think about hessians for more general potentials over time.

### CODE REVIEW

**Comment by git4lei** [comment]
Thanks a lot! 
Lei

**Comment by cortner** [comment]
Actually the bug was at my end - the cutoff was wrong.

What do you think, should we return to the nucleotiin project?

**Comment by git4lei** [comment]
That will be great, my term will finish (I taught two courses this term) this week, and I will start to look at the code from next week.
Shall we have a skype meeting sometime next week?

Lei

**Comment by cortner** [comment]
next week is pretty bad - how is the week after?

**Comment by git4lei** [comment]
The week after I will be in a workshop in Brown University, it will be okay for me after Tuesday (June 6).

**Pull request merged**
